### ISSUE TITLE
Library not building with JDK7

### ISSUE THREAD

**Issue by raskasa** [raskasa/metrics-okhttp#15]
When I run `mvn clean test` from the terminal, it builds successfully.
When I try to run any unit tests via IntelliJ, I get the following error:

```
Information:Using Eclipse compiler to compile java sources
Information:Module "metrics-okhttp" was fully rebuilt due to project configuration/dependencies changes
Information:7/19/15, 11:22 PM - Compilation completed with 10 errors and 0 warnings in 3s 902ms

/Users/Kasa/IdeaProjects/metrics-okhttp/src/test/java/com/raskasa/metrics/okhttp/InstrumentedOkHttpClientsTest.java
Error:(1, 1) java: The type java.util.Optional cannot be resolved. It is indirectly referenced from required .class files
Error:(1, 1) java: The type java.util.OptionalDouble cannot be resolved. It is indirectly referenced from required .class files
Error:(1, 1) java: The type java.util.OptionalInt cannot be resolved. It is indirectly referenced from required .class files
Error:(1, 1) java: The type java.util.OptionalLong cannot be resolved. It is indirectly referenced from required .class files
Error:(1, 1) java: The type java.time.ZonedDateTime cannot be resolved. It is indirectly referenced from required .class files
Error:(1, 1) java: The type java.time.LocalDateTime cannot be resolved. It is indirectly referenced from required .class files
Error:(1, 1) java: The type java.time.OffsetDateTime cannot be resolved. It is indirectly referenced from required .class files
Error:(1, 1) java: The type java.time.OffsetTime cannot be resolved. It is indirectly referenced from required .class files
Error:(1, 1) java: The type java.time.LocalTime cannot be resolved. It is indirectly referenced from required .class files
Error:(1, 1) java: The type java.time.LocalDate cannot be resolved. It is indirectly referenced from required .class files
```

After trying to run any unit tests via IntelliJ, if I go back to the terminal and try to run `mvn test` (note that a `clean` isn't run), I get the following errors:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.raskasa.metrics.okhttp.InstrumentedOkHttpClientsTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.07 sec <<< FAILURE!
createWithClient(com.raskasa.metrics.okhttp.InstrumentedOkHttpClientsTest)  Time elapsed: 0.008 sec  <<< ERROR!
java.lang.Error: Unresolved compilation problems: 
        The type java.util.Optional cannot be resolved. It is indirectly referenced from required .class files
        The type java.util.OptionalDouble cannot be resolved. It is indirectly referenced from required .class files
        The type java.util.OptionalInt cannot be resolved. It is indirectly referenced from required .class files
        The type java.util.OptionalLong cannot be resolved. It is indirectly referenced from required .class files
        The type java.time.ZonedDateTime cannot be resolved. It is indirectly referenced from required .class files
        The type java.time.LocalDateTime cannot be resolved. It is indirectly referenced from required .class files
        The type java.time.OffsetDateTime cannot be resolved. It is indirectly referenced from required .class files
        The type java.time.OffsetTime cannot be resolved. It is indirectly referenced from required .class files
        The type java.time.LocalTime cannot be resolved. It is indirectly referenced from required .class files
        The type java.time.LocalDate cannot be resolved. It is indirectly referenced from required .class files

        at com.raskasa.metrics.okhttp.InstrumentedOkHttpClientsTest.<init>(InstrumentedOkHttpClientsTest.java:1)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
        at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

createWithoutClient(com.raskasa.metrics.okhttp.InstrumentedOkHttpClientsTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.Error: Unresolved compilation problems: 
        The type java.util.Optional cannot be resolved. It is indirectly referenced from required .class files
        The type java.util.OptionalDouble cannot be resolved. It is indirectly referenced from required .class files
        The type java.util.OptionalInt cannot be resolved. It is indirectly referenced from required .class files
        The type java.util.OptionalLong cannot be resolved. It is indirectly referenced from required .class files
        The type java.time.ZonedDateTime cannot be resolved. It is indirectly referenced from required .class files
        The type java.time.LocalDateTime cannot be resolved. It is indirectly referenced from required .class files
        The type java.time.OffsetDateTime cannot be resolved. It is indirectly referenced from required .class files
        The type java.time.OffsetTime cannot be resolved. It is indirectly referenced from required .class files
        The type java.time.LocalTime cannot be resolved. It is indirectly referenced from required .class files
        The type java.time.LocalDate cannot be resolved. It is indirectly referenced from required .class files

        at com.raskasa.metrics.okhttp.InstrumentedOkHttpClientsTest.<init>(InstrumentedOkHttpClientsTest.java:1)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
        at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

But running `mvn clean test` will resolve the errors.

The TravisCI build fails for `oraclejdk7` with the following error:

```
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ metrics-okhttp ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/travis/build/raskasa/metrics-okhttp/target/test-classes
An exception has occurred in the compiler (1.7.0_76). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.util.Optional not found
```

NOTES:
* I have both Java 7 and 8 installed on my workstation.
* `JAVA_HOME` and `JAVA8_HOME` is set to my Java 8 installation.  `JAVA7_HOME` is set to my Java 7 installation.
* The Project Level and Project SDK via IntelliJ are set to Java 7.
* The Maven Compiler Plugin's source and target level are set to `1.7`.

**Comment by raskasa** [comment]
Just a reminder, the site lists explicitly that Java 8 is needed for 3.x:

![assertj](https://cloud.githubusercontent.com/assets/1843059/9119028/894b0fa2-3c42-11e5-9d1a-66598a36960d.PNG)

Also, dropwizard/metrics#850 can provide good context as well.
